### ISSUE TITLE
can't find variable structuredclone

### ISSUE THREAD

**Issue by michaelmain24** [pathofleastresistor/polr-ytube-media-card#13]
When using the code on IOS homeassiant , it will appear  "can't find variable structuredclone"
![檔案_000](https://github.com/pathofleastresistor/polr-ytube-media-card/assets/95572683/a9c1d5ec-9fa3-4a8a-bd83-d2070602cf90)

**Comment by pathofleastresistor** [comment]
Can you confirm what version of iOS you're on? I'm wondering if its >15.4 since that is when support for [structuredClone](https://developer.mozilla.org/en-US/docs/Web/API/structuredClone) was added.

**Comment by michaelmain24** [comment]
you are right ,I didn’t update ,thanks

**Comment by pathofleastresistor** [comment]
Great - I'll close this out
