### ISSUE TITLE
Volume doesnt work when streaming to Owntone server

### ISSUE THREAD

**Issue by nawaidrana** [pathofleastresistor/polr-ytube-media-card#15]
In addition, cannot cast to any sonos speakers, they do show up in the stream output but nothing plays. When selecting Owntone server, it plays on my sonos (as I have created an automation for owntone server as per ytube music documentation) but volume doesnt work.

Also, is there a way to select different output using owntone server? I have several sonos speakers.

**Comment by pathofleastresistor** [comment]
Sorry I'm not familiar with Owntone. I'm setting the volume of the media_player the ytube_music_player creates. Can you confirm if that works for you?

**Comment by KoljaWindeler** [comment]
Hi @nawaidrana , can you set the volume on the own tunes entity directly? Is that working? @pathofleastresistor is sending the command to me and I forward it to the owntones entity.. so we have to understand what is working and what is not

**Comment by pathofleastresistor** [comment]
Closing this and would recommend resolving this with https://github.com/KoljaWindeler/ytube_music_player first.
