### ISSUE TITLE
Scrollbars

### ISSUE THREAD

**Issue by KoljaWindeler** [pathofleastresistor/polr-ytube-media-card#2]
Hi, not sure if this is something you can change .. but on my laptop I get scrollbars. Is it possible to avoid that? Works fine on the phone
![17041199011887834844586795983890](https://github.com/pathofleastresistor/polr-ytube-media-card/assets/471314/0bc9dd64-ef36-43b2-b21b-a883b9394c80)
Thanks

**Comment by pathofleastresistor** [comment]
What browser/OS are you using? I'm developing on my Macbook and can't reproduce that in Chrome, Firefox, or Safari.

**Comment by KoljaWindeler** [comment]
Chrome on Ubuntu

![image](https://github.com/pathofleastresistor/polr-ytube-media-card/assets/471314/c44ed1dc-609e-453d-a494-a136daee4120)

**Comment by pathofleastresistor** [comment]
Fixed by https://github.com/pathofleastresistor/polr-ytube-media-card/commit/83580880605a77e214d5186edeca6a891eab0673

**Comment by KoljaWindeler** [comment]
Works fine with 1.5.1, thx
