### ISSUE TITLE
Songs only can see in alphabetical order.

### ISSUE THREAD

**Issue by ohnggni** [pathofleastresistor/polr-ytube-media-card#23]
Thank you for your great card, first. It is really great for me.
One thing I wanna suggest is that I'd like to see the songs in playlist as they are originally seen in order in my playlist in youtube.

Can you consider this?

**Comment by pathofleastresistor** [comment]
Can you see if changing the sort setting in the ytube_media_player configuration addresses your question:

https://github.com/pathofleastresistor/polr-ytube-media-card/assets/91756648/a9e7538b-8375-45c2-9f6b-16c5489bd870

**Comment by ohnggni** [comment]
> Can you see if changing the sort setting in the ytube_media_player configuration addresses your question:
> 
>  Screen.Recording.2024-02-11.at.5.01.51.PM.mov

It works! Thanks!
