### ISSUE TITLE
Adding Libraries with many items

### ISSUE THREAD

**Issue by dugdathug** [pathofleastresistor/polr-ytube-media-card#24]
Fantastic job on the card(s) - I'm a newbie to HA and am really getting into it - thanks a ton.  I did note that when I add a Library Playlist from my youtube Music (my Likes), it only adds the first 25 items to the queue.  Is this a limit that I can change?  Or is this baked into some other bit of the stack that you nor I have access to?

**Comment by pathofleastresistor** [comment]
Yes you'll need to adjust the configuration of the ytube_music_player. If you go to the advanced settings of the integration you can change the default from 25 to a larger number.

**Comment by pathofleastresistor** [comment]
Closing out. Please open an issue with https://github.com/KoljaWindeler/ytube_music_player if you need additional help
