### ISSUE TITLE
Playlists and Search don't load with Unknown Error

### ISSUE THREAD

**Issue by chaimchaikin** [pathofleastresistor/polr-ytube-media-card#3]
This seems really cool, excited to try it.
When browsing playlists or attempting to search I get "Unknown Error"
The media entity is correctly pulling in the right ytube music player (the song playing and controls work as expected)

In logs there is the following error:

```
Logger: homeassistant.components.websocket_api.http.connection
Source: components/media_player/__init__.py:1298
Integration: Home Assistant WebSocket API ([documentation](https://rc.home-assistant.io/integrations/websocket_api), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22))
First occurred: 7:07:10 PM (1 occurrences)
Last logged: 7:07:10 PM

[547462357568] Error handling message: Unknown error (unknown_error) Name from <<IP ADDRESS>> (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 26, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 1298, in websocket_browse_media
    if MediaPlayerEntityFeature.BROWSE_MEDIA not in player.supported_features:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'int' is not iterable
```

Versions:
Home Assistant 2024.1.0b3
yTube Music Player 20240101.01

**Comment by chaimchaikin** [comment]
I noticed the same error on browsing media directly on yTube Music Player so it's likely related to that component directly

**Comment by KoljaWindeler** [comment]
This https://github.com/KoljaWindeler/ytube_music_player/commit/e905d3ea19d656d6d15bbc898a3d031bbc1c6d20 might fix it .. not sure.

how did you trigger the issue? I can't see it here .. any special version of HA required?

**Comment by chaimchaikin** [comment]
> This [KoljaWindeler/ytube_music_player@e905d3e](https://github.com/KoljaWindeler/ytube_music_player/commit/e905d3ea19d656d6d15bbc898a3d031bbc1c6d20) might fix it .. not sure.
> 
> how did you trigger the issue? I can't see it here .. any special version of HA required?

On the beta 2024.1.0b3
Was working for me prior to updating to that, however I updated to the newest version of ytubemusic at the same time so I wasn't sure which caused it
