### ISSUE TITLE
Navigation

### ISSUE THREAD

**Issue by KoljaWindeler** [pathofleastresistor/polr-ytube-media-card#4]
Hi, why is there this "hamburger" icon to enter an item.
Why don't we simply click on the text ? 
![image](https://github.com/pathofleastresistor/polr-ytube-media-card/assets/471314/81a198a5-46b4-441c-993f-bd66bf6e2641)

Maybe there is a good reason :)

**Comment by pathofleastresistor** [comment]
So I have been thinking about better UX here.

The premise behind the current design is about deterministic behavior. Users should know if something is expandable compared to a similar looking thing that is not expandable.

The Media Browser does this on the desktop but doesn't from the mobile app.

The most obvious choice is additional buttons, but that's not always the most visually appealing.

Conclusion is there's room for improvement from today which is mostly functional.

**Comment by KoljaWindeler** [comment]
agreed .. just my 2 cents: I've tried multiple times to "click" on the name .. assuming that I can expand it .. and then remembered that this is not how it works. 
Maybe have the text bold if it is expandable?

**Comment by pathofleastresistor** [comment]
Here's an improved version that takes up a little more horizontal space.

[screenity.webm](https://github.com/pathofleastresistor/polr-ytube-media-card/assets/91756648/2d94d216-21d4-4e1c-91c7-7372e70f53e2)

**Comment by pathofleastresistor** [comment]
1.6.0 introduces the new list layout. I may eventually drop the primary icon based on the Material spec.
