### ISSUE TITLE
Idea: cover based navigation?

### ISSUE THREAD

**Issue by KoljaWindeler** [pathofleastresistor/polr-ytube-media-card#8]
Hi, just an in idea .. have you considered to (offer the option to) change from a line base navigation to a more cover flow oriented one?
so from this 
![image](https://github.com/pathofleastresistor/polr-ytube-media-card/assets/471314/6f49edd8-0502-46e4-bcb1-12daa53005d7)

to this

![image](https://github.com/pathofleastresistor/polr-ytube-media-card/assets/471314/1eb0b2a5-4c6a-4865-8ad5-18ccd93fb2f7)

**Comment by pathofleastresistor** [comment]
I've made progress on this idea but still needs some polishing to make it ready to pull it in.

![grid-item](https://github.com/pathofleastresistor/polr-ytube-media-card/assets/91756648/4719a9b0-24de-46f2-9d49-f5326b347d28)

**Comment by KoljaWindeler** [comment]
<3

**Comment by pathofleastresistor** [comment]
v1.6.0 supports this. Add `coverNavigation: true` to the card config.
